version: "3"
services:

  lisk-faucet:
    image: lisk/faucet:latest
    depends_on:
      - faucet-cache
    ports:
      - "3200:3200"
    networks:
      - lisk-faucet
    restart: on-failure
    environment:
      - NODE_ENV=production
    env_file:
      - .env

  faucet-cache:
    image: redis:alpine
    networks:
      - lisk-faucet
    restart: on-failure

networks:
  lisk-faucet:
